---
environment_version: 2748b2b9208b7a274607aa05b51c756e 

cidr_networks:
  container: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

used_ips:
  - "172.29.236.0,172.29.236.200"
  - "172.29.240.0,172.29.240.200"
  - "172.29.244.0,172.29.244.200"
  - "172.29.248.0,172.29.248.200"

global_overrides:
  internal_lb_vip_address: 172.29.236.200
  external_lb_vip_address: 104.130.20.56
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        type: "raw"
        ip_from_q: "container"
        group_binds:
          - all_containers
          - hosts
    - network:
        container_bridge: "br-vxlan"
        container_interface: "eth10"
        type: "vxlan"
        ip_from_q: "tunnel"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-flat"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_interface: "eth2"
        type: "raw"
        ip_from_q: "storage"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - swift_proxy

infra_hosts:
  infra1:
    ip: 172.29.236.100
  infra2:
    ip: 172.29.236.101
  infra3:
    ip: 172.29.236.102

compute_hosts:
  compute1:
    ip: 172.29.236.120
  compute2:
    ip: 172.29.236.121

storage_hosts:
  cinder2:
    ip: 172.29.236.131
    container_vars:
      cinder_backends:
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMISCSIDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "{{ hostvars[inventory_hostname]['storage_address'] | default(hostvars[inventory_hostname]['storage_address']) }}"
  cinder1:
    ip: 172.29.236.130
    container_vars:
      cinder_backends:
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMISCSIDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "{{ hostvars[inventory_hostname]['storage_address'] | default(hostvars[inventory_hostname]['storage_address']) }}"

log_hosts:
  logging1:
    ip: 172.29.236.110

network_hosts:
  infra1:
    ip: 172.29.236.100
  infra2:
    ip: 172.29.236.101
  infra3:
    ip: 172.29.236.102

haproxy_hosts:
  loadbalancer1:
    ip: 172.29.236.200

